"""empty message

Revision ID: 938580f27da2
Revises: 2b7380507a71
Create Date: 2023-10-13 00:10:35.967119

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "938580f27da2"
down_revision = "2b7380507a71"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stores",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("schema", sa.String(length=256), nullable=False),
        sa.Column("host", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("host"),
        sa.UniqueConstraint("schema"),
        schema="shared",
    )
    op.create_index(
        op.f("ix_shared_stores_name"), "stores", ["name"], unique=True, schema="shared"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_shared_stores_name"), table_name="stores", schema="shared")
    op.drop_table("stores", schema="shared")
    # ### end Alembic commands ###
