"""empty message

Revision ID: 80832834e1fb
Revises: 3d2ce3cdcf72
Create Date: 2023-10-16 18:56:24.876916

"""
import sqlalchemy as sa
from alembic import op

from store_core.db.migrations.tenant import for_each_tenant_schema

# revision identifiers, used by Alembic.
revision = "80832834e1fb"
down_revision = "3d2ce3cdcf72"
branch_labels = None
depends_on = None


@for_each_tenant_schema
def upgrade(schema: str) -> None:
    preparer = sa.sql.compiler.IdentifierPreparer(op.get_bind().dialect)
    schema_quoted = preparer.format_schema(schema)

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "stores",
        "phone",
        existing_type=sa.VARCHAR(length=256),
        nullable=False,
        schema="shared",
    )
    op.add_column(
        "products",
        sa.Column("description", sa.String(length=200), nullable=True),
        schema=schema,
    )
    # ### end Alembic commands ###


@for_each_tenant_schema
def downgrade(schema: str) -> None:
    preparer = sa.sql.compiler.IdentifierPreparer(op.get_bind().dialect)
    schema_quoted = preparer.format_schema(schema)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "description", schema=schema)
    op.alter_column(
        "stores",
        "phone",
        existing_type=sa.VARCHAR(length=256),
        nullable=True,
        schema="shared",
    )
    # ### end Alembic commands ###
