"""empty message

Revision ID: 9279ef8a2e0a
Revises: 938580f27da2
Create Date: 2023-10-16 13:25:43.899329

"""
import sqlalchemy as sa
from alembic import op

from store_core.db.migrations.tenant import for_each_tenant_schema

# revision identifiers, used by Alembic.
revision = "9279ef8a2e0a"
down_revision = "938580f27da2"
branch_labels = None
depends_on = None


@for_each_tenant_schema
def upgrade(schema: str) -> None:
    preparer = sa.sql.compiler.IdentifierPreparer(op.get_bind().dialect)
    schema_quoted = preparer.format_schema(schema)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema=schema,
    )
    op.create_index(
        op.f(f"ix_store_products_name"),
        "products",
        ["name"],
        unique=True,
        schema=schema,
    )
    # ### end Alembic commands ###


@for_each_tenant_schema
def downgrade(schema: str) -> None:
    preparer = sa.sql.compiler.IdentifierPreparer(op.get_bind().dialect)
    schema_quoted = preparer.format_schema(schema)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f(f"ix_store_products_name"),
        table_name="products",
        schema=schema,
    )
    op.drop_table("products", schema=schema)
    # ### end Alembic commands ###
