"""empty message

Revision ID: 3d2ce3cdcf72
Revises: 9279ef8a2e0a
Create Date: 2023-10-16 18:29:38.993469

"""
import sqlalchemy as sa
from alembic import op

from store_core.db.migrations.tenant import for_each_tenant_schema

# revision identifiers, used by Alembic.
revision = "3d2ce3cdcf72"
down_revision = "9279ef8a2e0a"
branch_labels = None
depends_on = None


@for_each_tenant_schema
def upgrade(schema: str) -> None:
    preparer = sa.sql.compiler.IdentifierPreparer(op.get_bind().dialect)
    schema_quoted = preparer.format_schema(schema)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stores",
        sa.Column("phone", sa.String(length=256), nullable=True),
        schema="shared",
    )
    op.create_unique_constraint(None, "stores", ["phone"], schema="shared")
    op.alter_column(
        "products",
        "name",
        existing_type=sa.VARCHAR(length=256),
        type_=sa.String(length=128),
        existing_nullable=False,
        schema="store_default",
    )
    op.drop_index(
        "ix_store_products_name", table_name="products", schema="store_default"
    )
    op.create_unique_constraint(None, "products", ["name"], schema="store_default")
    # ### end Alembic commands ###


@for_each_tenant_schema
def downgrade(schema: str) -> None:
    preparer = sa.sql.compiler.IdentifierPreparer(op.get_bind().dialect)
    schema_quoted = preparer.format_schema(schema)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "products", schema="store_default", type_="unique")
    op.create_index(
        "ix_store_products_name",
        "products",
        ["name"],
        unique=False,
        schema="store_default",
    )
    op.alter_column(
        "products",
        "name",
        existing_type=sa.String(length=128),
        type_=sa.VARCHAR(length=256),
        existing_nullable=False,
        schema="store_default",
    )
    op.drop_constraint(None, "stores", schema="shared", type_="unique")
    op.drop_column("stores", "phone", schema="shared")
    # ### end Alembic commands ###
